# conex�o com banco
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore-jpa
spring.datasource.username=postgres
spring.datasource.password=xxt12120405

# driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA (opcional, mas recomendado)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true